version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"    
    environment:
      MARIADB_ROOT_PASSWORD: pass
    volumes:
      - ./db:/var/lib/mysql    
  
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
      restart: always
      ports:
          - 8181:80
      volumes:
          - /sessions
      links:
          - db      

  php-apache:
    image: webdevops/php-apache-dev:7.4-alpine            
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./app:/app    
    links:
      - db


#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

