version: '3.1'

services:

  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret_pass
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=web_user
      - MYSQL_PASSWORD=pass
    expose:
      - 3306
      - 33060
  
  php-apache:    
    image: webdevops/php-apache-dev:8.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app:/app    
    environment:
     - LOG_STDOUT=/app/logs/app-log.log
     - LOG_STDERR=/app/logs/app-log-errors.log
    links:
      - db
    
  phpmyadmin:
      image: phpmyadmin:latest
      container_name: phpmyadmin
      environment:
          - MYSQL_ROOT_PASSWORD=secret_pass
          - MYSQL_USER=web_user
          - MYSQL_PASSWORD=pass
          - APACHE_PORT=80
      restart: always
      ports:
          - 8181:80
      volumes:
          - /sessions
      links:
          - db   

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    
